"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const threads = __importStar(require("./threads"));
exports.LOAD_SUMMERY_WEIGHT = 0.99;
exports.GROUP_ADDR_PRE = "g";
exports.REACTOR_ADDR_PRE = "r";
exports.WORKER_FILE_PATH = __dirname + "/worker.js";
var actor_1 = require("./actor");
exports.Actor = actor_1.Actor;
exports.ActorMessage = actor_1.ActorMessage;
var addr_1 = require("./addr");
exports.Addr = addr_1.Addr;
var orchestrator_1 = require("./orchestrator");
exports.Orchestrator = orchestrator_1.Orchestrator;
var reactor_1 = require("./reactor");
exports.Reactor = reactor_1.Reactor;
var Validation;
(function (Validation) {
    Validation.ThreadActorMessage = threads.ThreadActorMessage;
    Validation.ThreadActorResponse = threads.ThreadActorResponse;
    Validation.ThreadDestroyMessage = threads.ThreadDestroyMessage;
    Validation.ThreadMessageType = threads.ThreadMessageType;
    Validation.ThreadSpawnMessage = threads.ThreadSpawnMessage;
    Validation.ThreadSpawnedMessage = threads.ThreadSpawnedMessage;
    Validation.ThreadStatsMessage = threads.ThreadStatsMessage;
    Validation.parseThreadMessage = threads.parseThreadMessage;
})(Validation = exports.Validation || (exports.Validation = {}));
